### ISSUE TITLE
question for Set up configuration file

### ISSUE THREAD

**Issue by landsat12** [JGCRI/xanthos#19]

**Comment by landsat12** [comment]
Dear colleague,
When I run` xth = run(ini)`, I recevied error :
```
  File "build\bdist.win-amd64\egg\xanthos\data_reader\ini_reader.py", line 27, in __init__
    p = c['Project']

  File "build\bdist.win-amd64\egg\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)

KeyError: 'Project'
```
Is that anything wrong? 
Thank you very much for your help!

**Comment by calebbraun** [comment]
It looks like either your config file is not set up correctly or cannot be found. Make sure the first line of your config is `[Project]` and that your variable `ini` is the full path to your config file.

**Comment by landsat12** [comment]
Ok, Thank you ! I set up my  config file again. And I run the examply.py. New erro
 `File "build\bdist.win-amd64\egg\xanthos\data_reader\ini_reader.py", line 34, in __init__
    self.OutDir = self.create_dir(os.path.join(self.root, p['OutputFolder']))

  File "build\bdist.win-amd64\egg\xanthos\data_reader\ini_reader.py", line 619, in create_dir
    os.mkdir(pth)

WindowsError: [Error 3] : '/Users/d3y010/repos/github/xanthos/example\\output'`
occur.
 It Looks like the path cannot be found.  But this path is not my dir path. My dir path is 'D:\\Zongshuo\\GHM\\xanthos\\example\\pm_abcd_mrtm.ini' 
 Thank you for your help!

**Comment by calebbraun** [comment]
In your file, `D:\Zongshuo\GHM\xanthos\example\pm_abcd_mrtm.ini`, you need to update the example file paths to match your set up. This is probably something like changing line 7 in `pm_abcd_mrtm.ini` from:

`RootDir                     = /Users/d3y010/repos/github/xanthos/example`

to

`RootDir                     = D:\Zongshuo\GHM\xanthos\example`

Lines 143 and 146 need to be updated as well.

**Comment by landsat12** [comment]
thank you very much for your help!
