### ISSUE TITLE
git lfs clone fix

### ISSUE THREAD

**Issue by swd-turner** [JGCRI/xanthos#4]
`git lfs install`
`git clone https://github.com/JGCRI/xanthos.git`

When attempting the above from a windows shell, the download hangs.

Solution from [here ](https://github.com/git-lfs/git-lfs/issues/1821) is to use `git lfs clone https://github.com/JGCRI/xanthos.git`, which works. This should maybe be added to point 2 of getting started instructions.

**Comment by crvernon** [comment]
Added your suggestion to the docs.  Thanks!
