### ISSUE TITLE
output csvs unit column

### ISSUE THREAD

**Issue by swd-turner** [JGCRI/xanthos#5]
Currently the output csvs (e.g. `Basin_runoff_235_XXXX.csv`) have a final column header that specifies units (e.g., `Unit (km^3/year)`. This header doesn't actually refer to a column of data in the table, making the csv difficult to work with. I think the unit needs to be either:
(1) included as a full column,
(2) included as a comment at the top of the file (best option in my opinion), or
(3) included in the file name.

**Comment by crvernon** [comment]
@swd-turner @rplzzz This is addressed in the newer version that will be released soon.  The new runs that are to be archived will have the units in the file name and not in the file.  The # sign will also be removed from the first entry.

**Comment by crvernon** [comment]
Fix merged.
